blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include(('myapp.urls',"myapp"),namespace= "myapp")),
]

blog/myapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('0',views.index,name='0'),
    path('1',views.index1,name='1'),
    path('2',views.index2,name='2'),
    path('3',views.index3,name='3'),
    path('4',views.index4,name='4'),
    path('5',views.index5,name='5'),
    path('6',views.index6,name='6'),
    path('7',views.index7,name='7'),
    path('8', views.index8, name='8'),
    path('9', views.index9, name='9'),
    path('submit.html', views.submit, name='submit'),
    path('submit1.html', views.submit1, name='submit1'),
    path('finallyTable.html', views.finallyTable, name='finallyTable'),
]

blog/templates/ThreeFuc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>三个功能</title>
</head>
<body>
    <a href="submit.html">功能一</a><br>
    <a href="submit1.html">功能二</a><br>
    <a href="finallyTable.html">功能三</a><br>
</body>
</html>

blog/templates/finallyTable.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>纳税人信用指标权重确定</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'CreditRating.css' %}">

    

</head>

<body>
    <div id="boxA">
    
    </div>
    <button id="buttonA" onclick="MakeTableA()">生成A表</button>
    <button id="submissionA">提交A表</button>

    

    <br>

    <div id="boxS">
    
    </div>
    <button id="buttonS" onclick="MakeTableS()">生成S表</button>
    <button id="submissionS">提交S表</button>

    <button id="buttonSuanFa">运行算法</button>

     {% load staticfiles %}
    <script src="{% static 'finally.js' %}"></script>
</body>

</html>


blog/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'submit.css' %}">
    <script src="{% static 'submit.js' %}"></script>
</head>
<body>
    <input type="button" value="打开文件">
    <input type="button" value="添加" id="btnadd"><br />

    <form action="" method="POST" name="tianxieS">
        {%  csrf_token %}
        <p>A表定义</p>
        <table id="tableOne" cellpadding='0' cellspacing='0'>
            <thead>
                    <td>语言项</td>
                    <td>意义</td>
                    <td>操作</td>
            </thead>
            <tbody id="itbody">

            </tbody>
        </table>
        <input type="button" value="提交表单" name="submitIT" id="submitIT">
    </form>
</body>
</html>

blog/templates/submit1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'submit.css' %}">
    <script src="{% static 'submit1.js' %}"></script>
</head>
<body>
    <input type="button" value="打开文件">
    <input type="button" value="添加" id="btnadd"><br />

    <form action="" method="POST" name="tianxieS">
        {%  csrf_token %}
        <p>S表定义</p>
        <table id="tableOne" cellpadding='0' cellspacing='0'>
            <thead>
                    <td>语言项</td>
                    <td>意义</td>
                    <td>操作</td>
            </thead>
            <tbody id="itbody">

            </tbody>
        </table>
        <input type="button" value="提交表单" name="submitIT" id="submitIT">
    </form>
</body>
</html>

blog/templates/web1.html
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Upload Successfully</title>
    </head>
    <body>
        <p>学生名单</p>
        jQuery.ajax({ url:index/ type:'get'})
        jQuery.ajax({ url:index/1 type:'get'})
    </body>
</html>

blog/templates/web2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>请输入新的内容</title>
</head>
<body>
    <form action="{% url 'myapp:3' %}" method="post">
        {%  csrf_token %}
        <input type="text" name="input[]">
        <input type="text" name="input[]">
        <br/>
        <input type="text" name="input[]">
        <input type="text" name="input[]">
        <br/>
        <input type="text" name="input[]">
        <input type="text" name="input[]">
        <br/>
        <input type="text" name="input[]">
        <input type="text" name="input[]">
        <br/>
        <input type="submit"value="提交">
    </form>
</body>
</html>